/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://eqp3mwroxffevkhn6xbfjiwxx4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vqeik76w65chbirfjszgbyolcy",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Attendance",
            "region": "us-east-1"
        },
        {
            "tableName": "FaceIndex",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
